### ISSUE TITLE
Potential preset issue 

### ISSUE THREAD

**Issue by MaliciousUpload** [alphabotsystem/Alpha#12]
User: 
> preset add cryptos c btcusdt 15m, c ethusdt 15m, c ltcusdt 15m, c bchabcusdt 15m, c bnbusdt 15m

Alpha:
> A command cannot be used as a preset name.

User:
> preset add coins c btcusdt 15m, c ethusdt 15m, c ltcusdt 15m, c bchabcusdt 15m, c bnbusdt 15m

Alpha:
> A command cannot be used as a preset name.

If there are certain terms that can not be used then they should be included in the *preset help* context as words not able to be used in a preset name and even then i dont like the idea of banning certain words **UNLESS** it is for system purposes. As we will eventually end up with a massive list of words that *trigger* X, Y, Z people

**Comment by MaticConradi** [comment]
This is a bug. An error message (which should be rephrased) is appearing even though it shouldn’t

**Comment by MaticConradi** [comment]
Fixed
