### ISSUE TITLE
Orderbook preset issue

### ISSUE THREAD

**Issue by MaliciousUpload** [alphabotsystem/Alpha#13]
User:

> books

Alpha:

> Running `d binance:btcusdt, d bitmex:xbtusd, d huobi:ethusdt` command from preset

no response after that

ran `d btcusdt` just to unsure it wasnt the orderbook command itself and that single orderbook came through fine

**Comment by MaliciousUpload** [comment]
I can now see that Alpha is unable to pull Huobi's orderbook because they dont provide that data to TV but after changing the preset to only contain  `d binance:btcusdt, d bitmex:xbtusd` I am still not receiving a response from Alpha

**Comment by MaticConradi** [comment]
The syntax is invalid
