### ISSUE TITLE
Alert list sorting

### ISSUE THREAD

**Issue by MaliciousUpload** [alphabotsystem/Alpha#15]
When the user uses the `alert list` command the alerts are listed in this format:

`Ticker exchange price`

```
BTCUSDT Binance 10350

BTCUSDT Coinbase 10350

BTCUSDT Kraken 12500

XBTUSD Bitmex 10500

XBTUSD Bitmex 10400

**Comment by MaticConradi** [comment]
Alerts will be formatted in order `exchange` > `market ticker` > `trigger price`

**Comment by MaticConradi** [comment]
Added
