### ISSUE TITLE
Command added for options trading history

### ISSUE THREAD

**Issue by HaydenSander** [alphabotsystem/Alpha#20]
User has requested new feature added to Alpha for the recent trades of options which can be seen from this site here [:](traceoption.com)
![image](https://user-images.githubusercontent.com/39495762/66675325-faf1d100-ec19-11e9-9ce3-3ac46bd57beb.png)

the command would go something along these lines

user: `O flow`

Alpha: would then display the list shown in the screenshot above

or 

user: `O AAPL`

Alpha: would then display only any Apple trades in recent history

**Comment by MaticConradi** [comment]
O is a bad prefix generally speaking. As long as is the number of arguments fixed, it might work, but that needs some further discussion
