### ISSUE TITLE
Ability to add different syntax type functions into a single preset

### ISSUE THREAD

**Issue by MaliciousUpload** [alphabotsystem/Alpha#21]
example:

User: preset add shorttermBTC c xbtusd 5m, d xbtusd, p xbt oi, v xbt

Alpha then posts all of the function types listed above in a single preset when the user requests that preset. This will create a good amount of convenience for the user and also give more functionality to the preset function itself.

**Comment by MaticConradi** [comment]
Will require a rewrite of the message parser. Closed for now, will reopen once relevant
