### ISSUE TITLE
Add a "premium futures" command

### ISSUE THREAD

**Issue by HaydenSander** [alphabotsystem/Alpha#28]
User:
> premium xbt

Alpha:
> XBTUSD
> BitMEX: 6852.5 USD
> Bitfinex: -75.70 USD (-1.09 %)
> Coinbase Pro: -8.73 USD (-0.13 %)
> Binance: +6.04 USDT (+0.09 %)
> Huobi Pro: +4.78 USDT (+0.07 %)
> Premiums across exchanges

User:
> premium futures

Alpha:
> Bitmex
> XBTUSD: 6852.5 USD
> XBTZ19: -7.50 USD (-0.109 %)
> XBTH20: -0.85 USD (-0.013 %)
> Premiums between perps and futures

**Comment by MaticConradi** [comment]
Closing for now, may reopen later
