### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by trotter2000** [alphabotsystem/Alpha#30]
Forgive me but not a python man. But looks like there is an if and elif without anything to do if the condition is met?

  File "discord_alpha.py", line 3080
    elif method in ["delete", "remove"]:
       ^
IndentationError: expected an indented block

**Comment by MaticConradi** [comment]
You are correct. This repository is always lagging begind our full codebase, so this issue has been addressed on our end, but not here. You can comment out the entire if statement in that method and the issue should be resolved
